W6D5/w6d5/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats 
end

W6D5/w6d5/app/models/cat.rb
require 'action_view'
class Cat < ApplicationRecord
    include ActionView::Helpers::DateHelper

    validates :name, :color,  :description, :sex, :birth_date, presence: true

    validates :color, inclusion: { in: %w(white orange brown black polka-dot),message:"Is not a Valid Color"  }
    
    THE_SEXES = ['M','F']
    validates :sex, inclusion: {in: THE_SEXES, message: "%{value} Isn't a sex for kitty cats"}

    def age
        time_ago_in_words(birth_date)  
    end

end
# dd-mm-yyyy



# class Coffee < ApplicationRecord
#     validates :size, inclusion: { in: %w(small medium large),
#       message: "%{value} is not a valid size" }
# end

W6D5/w6d5/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    skip_before_action :verify_authenticity_token
end

W6D5/w6d5/app/controllers/cats_controller.rb
class CatsController < ApplicationController
    def index
        @cats = Cat.all
        #render json: @cats
        render :index
    end

    def show 
        @cat = Cat.find(params[:id]) 
        # render json: @cat 
        render :show
    end

    def new
        @cat = Cat.new #dummy cat
        render :new
    end
    # name: timmy 
    # color: black
    # sex:

    def create
        @cat = Cat.new(cat_params) ##

        if @cat.save
            redirect_to cat_url(@cat)
        else
            render :new
            #redirect_to new_cat_url
        end
    end

    def edit
        @cat = Cat.find(params[:id])
        render :edit
    end

    def update
        @cat = Cat.find(params[:id])

        if @cat.update(cat_params)
            redirect_to cat_url(@cat)
        else
            render :edit
        end

    end

    private
    def cat_params
        params.require(:cat).permit(:name,:color,:sex,:description,:birth_date)
    end
end

W6D5/w6d5/app/helpers/cats_helper.rb
module CatsHelper
end

W6D5/w6d5/app/views/cats/edit.html.erb
<h1> This Is Where You Edit a Kit Kat </h1>

<form action="<%= cat_url(@cat) %>" method="POST">
    <input type="hidden" name="_method" value="PATCH">
<br>
    <label for="name">Name:
        <input type="text" name="cat[name]" value="<%= @cat.name %>">
    </label>  
<br>
    <label for="color">Color:
        <select name="cat[color]">
            <option disabled selected>--This Is Default--</option>
            <option value="white">white</option>
            <option value="orange">orange</option>
            <option value="brown">brown</option>
            <option value="black">black</option>
            <option value="polka-dot">polka-dot</option>
        </select>
    </label>
<br>
    <label for="sex">Sex
        <input type="radio" name="cat[sex]" value="M"> Male
        <input type="radio" name="cat[sex]" value="F"> Female
    </label>
<br>

<!-- Cat.new(name, color, birth_date = "dd-mm-yyyy") "birth_date"=>"yyyy-mm-dd" -->
    <label for="birthday">Birth-Date:
        <input type="date" name="cat[birth_date]" value="2017-06-01">
    </label>
<br>
    <label for="description">Description:</label><br> 
    <textarea name="cat[description]">
    </textarea>
<br>
    <input type="submit" value="Update Kit Kat">
</form>

W6D5/w6d5/app/views/cats/index.html.erb
<h1> Test the Text. </h1>

<!-- ctrl + shift + `   <%#  %>  -->
<!-- pe, er-->

<ul>
    <%@cats.each do |cat|  %>
    <br>

    <a href="<%= cat_url(cat.id) %>">Go to <%= cat.name %>'s Page </a>
    <br>
    <a href="<%=edit_cat_url(cat.id)%>">Edit KitKat</a>
    <br>
    <br>
        <li>ID: <%= cat.id %> </li>
        <li>Name: <%= cat.name %></li>
        <li>Color: <%= cat.color %></li>
        <li>Sex: <%= cat.sex %></li>
        <li>Descrip: <%= cat.description %></li>
        <li>Birth_day: <%= cat.birth_date %></li>
        <li>Age: <%= cat.age %></li>
    <br>
    <% end%>
</ul>

W6D5/w6d5/app/views/cats/new.html.erb
<h1> This Is Where You Create A Kit-Kat </h1>

<form action="<%= cats_url %>" method="POST"> 
<br>
    <label for="name">Name:
        <input type="text" name="cat[name]" value="<%= @cat.name %>">
    </label>  
<br>
    <label for="color">Color:
        <select name="cat[color]">
            <option disabled selected>--This Is Default--</option>
            <option value="white">white</option>
            <option value="orange">orange</option>
            <option value="brown">brown</option>
            <option value="black">black</option>
            <option value="polka-dot">polka-dot</option>
        </select>
    </label>
<br>
    <label for="sex">Sex
        <input type="radio" name="cat[sex]" value="M"> Male
        <input type="radio" name="cat[sex]" value="F"> Female
    </label>
<br>

<!-- Cat.new(name, color, birth_date = "dd-mm-yyyy") "birth_date"=>"yyyy-mm-dd" -->
    <label for="birthday">Birth-Date:
        <input type="date" name="cat[birth_date]" value="2017-06-01">
    </label>
<br>
    <label for="description">Description:</label><br> 
    <textarea name="cat[description]">
    </textarea>
<br>
    <input type="submit" value="Create Kitty Kat">
</form>

W6D5/w6d5/app/views/cats/show.html.erb
<h1> <b><%= @cat.name %></b> the cat!</h1>
<a href="<%= cats_url %>">Go Back to Index</a>
<ul> 
    <li>Name: <%= @cat.name %></li>
    <li>Color: <%= @cat.color %></li>
    <li>Sex: <%= @cat.sex %></li>
    <li>Descrip: <%= @cat.description %></li>
    <li>Birth_day: <%= @cat.birth_date %></li>
    <li>Age: <%= @cat.age %></li>
</ul>

W6D5/w6d5/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>W6d5</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>