W8D1/RedditClone/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :show, :create, :destroy, :index]
  resource :session, only: [:new, :create, :destroy]
  resources :subs, except: [:destroy] do
    resources :posts, only: [:edit, :update]
  end
  resources :posts, except: [:index, :edit, :update]
end

W8D1/RedditClone/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

W8D1/RedditClone/app/models/post.rb
class Post < ApplicationRecord
    validates :title, presence: true


    belongs_to :sub,
        foreign_key: :sub_id,
        class_name: :Sub

    belongs_to :author,
        foreign_key: :author_id,
        class_name: :User,
        optional: true

end

W8D1/RedditClone/app/models/sub.rb
class Sub < ApplicationRecord
    validates :title, :description, :moderator_id, presence: true

    has_many :posts,
        foreign_key: :sub_id,
        class_name: :Post

    belongs_to :moderator,
        foreign_key: :moderator_id,
        class_name: :User
end

W8D1/RedditClone/app/models/user.rb
class User < ApplicationRecord
    validates :username, presence: true, uniqueness: true
    validates :password, length: {minimum: 6, allow_nil: true}
    validates :password_digest, presence: true
    validates :session_token, presence: true, uniqueness: true

    attr_reader :password
    before_validation :ensure_session_token

    #SPIRE

    def self.find_by_credentials(username, password)
        user = User.find_by(username: username)
        if !user
            return nil
        end

        return user.is_password?(password) ? user : nil
    end

    def password=(password)
        @password = password
        self.password_digest = BCrypt::Password.create(password)
    end

    def is_password?(password)
        BCrypt::Password.new(self.password_digest).is_password?(password)
    end

    def reset_session_token!
        self.session_token = SecureRandom::urlsafe_base64
        self.save!
        self.session_token
    end

    def ensure_session_token
        self.session_token ||= SecureRandom::urlsafe_base64
    end

    has_many :posts,
        foreign_key: :author_id,
        class_name: :Post

    has_many :subs,
        foreign_key: :moderator_id,
        class_name: :Sub

end

W8D1/RedditClone/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    #CRLLL
    helper_method :current_user, :logged_in?

    def current_user
        @current_user ||= User.find_by( session_token: session[:session_token] )
    end

    def require_logged_in?
        redirect_to new_session_url unless logged_in?
    end

    def login!(user)
        @current_user = user
        session[:session_token] = user.reset_session_token! 
    end

    def logout!
        current_user.reset_session_token! if logged_in?
        current_user = nil
        session[:session_token] = nil
    end

    def logged_in?
        !!current_user
    end

    def is_moderator?(sub)
        logged_in? && current_user.id == sub.moderator_id
    end

    def is_author?(post)
        logged_in? && current_user.id == post.author_id
    end
end

W8D1/RedditClone/app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def new
        @post = Post.new(post_params)
        render :new
    end
    
    def show
        
    end
    
    def create
        @post = Post.new(post_params)
        @post.author_id = current_user.id
        if @post.save
            redirect_to post_url(@post)
        else

        end
    end
    
    def edit
        @post = Post.find(params[:id])

        if is_author?(@post)
            render :edit
        else
            flash[:errors] = ["Only post authors can edit posts."]
            redirect_to sub_url(@post.sub)
        end
    end

    def update
        @post = Post.find(params[:id])
        if is_author?(@post)            
            if @post.update(post_params)
                redirect_to post_url(@post)
            else
                flash.now[:errors] = @post.errors.full_messages
                render :edit
            end
        else 
            flash[:errors] = ["Only post authors can edit posts."]
            redirect_to sub_url(@post.sub)
        end
    end

    def destroy

    end

    def post_params
        params.require(:post).permit(:title, :url, :content, :sub_id)
    end
end

W8D1/RedditClone/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    before_action :require_logged_in?, only: [:destroy]

    def new
        render :new
    end

    def create
        @user = User.find_by_credentials(
            params[:user][:username],
            params[:user][:password]
        )
        if @user
            login!(@user)
            redirect_to user_url(@user)
        else
            flash[:errors] = ["Credentials Failed, 3 trys left."]
            render :new
        end
        
    end

    def destroy
        logout!
        redirect_to new_session_url
    end
end

W8D1/RedditClone/app/controllers/subs_controller.rb
class SubsController < ApplicationController
    before_action :require_logged_in?, except: [:show, :index]

    def new
        render :new
    end
    def show
        @sub = Sub.find(params[:id])
        render :show
    end
    def create
        @sub = Sub.new(sub_params)
        @sub.moderator_id = current_user.id
        if @sub.save
            redirect_to sub_url(@sub)
        else
            flash.now[:errors] = @sub.errors.full_messages
            render :new
        end
    end

    def edit
        @sub = Sub.find(params[:id])
        if is_moderator?(@sub)
            render :edit
        else
            flash[:errors] = ["You do not have permission to edit this sub!"]
            redirect_to subs_url
        end
    end

    def update
        @sub = Sub.find(params[:id])
        if is_moderator?(@sub)            
            if @sub.update(sub_params)
                redirect_to sub_url(@sub)
            else
                flash.now[:errors] = @sub.errors.full_messages
                render :edit
            end
        else 
            flash[:errors] = ["You do not have permission to edit this sub!"]
            redirect_to subs_url
        end
    end
    def index
        @subs = Sub.all
        render :index
    end
    private
    def sub_params
        params.require(:sub).permit(:title, :description)
    end
end

W8D1/RedditClone/app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :require_logged_in?, only: [:show, :index]

    def new
        @user = User.new
        render :new
    end

    def show
        @user = User.find(params[:id])
        render :show
    end
    
    def index      
        @users = User.all
        render :index
    end

    def create
        @user = User.new(user_params)
        if @user.save
            login!(@user)
            redirect_to user_url(@user)
        else
            flash.now[:errors] = @user.errors.full_messages
            render :new
        end
    end

    def user_params
        params.require(:user).permit(:password, :username)
    end

end

W8D1/RedditClone/app/helpers/application_helper.rb
module ApplicationHelper
end

W8D1/RedditClone/app/helpers/posts_helper.rb
module PostsHelper
end

W8D1/RedditClone/app/helpers/sessions_helper.rb
module SessionsHelper
end

W8D1/RedditClone/app/helpers/subs_helper.rb
module SubsHelper
end

W8D1/RedditClone/app/helpers/users_helper.rb
module UsersHelper
end

W8D1/RedditClone/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <!-- Different display if we are logged in or not -->

    <!-- Logged In: -->
    <!-- Display username, Log out button -->
    <% if logged_in? %>
      <p>Logged in as: <%= current_user.username %></p>
      <form action="<%= session_url %>" method="POST">
        <input type="hidden" name="_method" value="DELETE">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" >
        <input type="submit" value="Sign Out">
      </form>
    <% else %>

    <% end %>

    <% if flash[:errors] %>
      <p><%= flash[:errors].join(", ") %></p>
    <% end%>

    <%= yield %>
  </body>
</html>

W8D1/RedditClone/app/views/posts/new.html.erb
<h1>New Post</h1>

<!-- Button that appears on the new_session page. Post a new session-->
<form action="<%= posts_url %>" method="POST">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" >

    <label>Title:
    <input type="text" name="post[title]" value="">
    </label>

    <label>URL (optional):
    <input type="text" name="post[url]" value="">
    </label>

    <label>Content (optional):
    <input type="text" name="post[content]" value="">
    </label>

    <input type="hidden" name="post[sub_id]" value="<%= @post.sub_id %>">



    <button type="submit">Create Post</button>
</form>

W8D1/RedditClone/app/views/subs/edit.html.erb
<h1>Edit the Subreddit</h1>

<form action="<%= sub_url(@sub) %>" method="POST">
    <input type="hidden" name="_method" value="PATCH">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" >

    <label>Title:
    <input type="text" name="sub[title]" value="<%= @sub.title %>">
    </label>

    <label>Description:
    <input type="text" name="sub[description]" value="<%= @sub.description %>">
    </label>

    <button type="submit">Edit the Subreddit</button>
</form>

W8D1/RedditClone/app/views/subs/index.html.erb
<h1>All the subs and their moderators</h1>

<% @subs.each do |sub| %>
<a href="<%= sub_url(sub) %>"><%= sub.title %></a>
<br>
Mod: <%= sub.moderator.username %>
<br>
<% end %>

W8D1/RedditClone/app/views/subs/new.html.erb
<h1>Create a Subreddit</h1>

<!-- Button that appears on the new_session page. Post a new session-->
<form action="<%= subs_url %>" method="POST">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" >

    <label>Title:
    <input type="text" name="sub[title]" value="">
    </label>

    <label>Description:
    <input type="text" name="sub[description]" value="">
    </label>

    <button type="submit">Create a Subreddit</button>
</form>

W8D1/RedditClone/app/views/subs/show.html.erb
<h1>This is the Subreddit: <%= @sub.title %></h1>
<br>
    <h2>Description:<%= @sub.description %></h2>
<br>

    <form action="<%= new_post_url %>" method="GET">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" >
        <input type="hidden" name="post[sub_id]" value="<%= @sub.id %>">
        <button type="submit">New Post</button>
    </form>
<br>

All the posts

<% @sub.posts.each do |post| %>
 Title: <a href="<%= post_url(post) %>"><%= post.title%></a>
 <% end %>

<br>
<a href="<%= subs_url %>">Back to all subreddits</a>

W8D1/RedditClone/app/views/users/index.html.erb
<h1> All of our users  </h1>
<%@users.each do |user|  %>
    Username: <a href="<%= user_url(user) %>"><%= user.username %></a>
    Id: <%= user.id %>
<% end  %>

W8D1/RedditClone/app/views/users/new.html.erb
<h1>Create An Account</h1>
<form action="<%= users_url %>" method="POST">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" >

    <label>Username: 
    <input type="text" name="user[username]" value="">
    </label>

    <label>Password:
    <input type="password" name="user[password]" value="">
    </label>

    <button type="submit">Create Account</button>
</form>

W8D1/RedditClone/app/views/users/show.html.erb
<h1>This is the page of <%= @user.username %></h1>
<br>

<% unless @user.subs.length == 0%>
    <%= @user.username %> is the Moderator of:
    <br>
    <% @user.subs.each do |sub| %>
        <a href="<%= sub_url(sub) %>"><%= sub.title %></a>
        <br>
    <% end %>
<% end %>

<a href="<%= users_url %>">Back to all users</a>